# дефолтные значения переменных
---
# list of username or %groupname
sudo_users: []
# list of username or %groupname and their defaults
sudo_defaults: []
# default sudoers file
sudo_sudoers_file: ansible

stand_setup_user_pubkeys_path: '{{ role_path }}/files/pubkeys'

ntp_enabled: true

ntp_timezone: Europe/Moscow

# NTP server area configuration (leave empty for 'Worldwide').
# See: http://support.ntp.org/bin/view/Servers/NTPPoolServers
ntp_area: ''
ntp_servers:
  - "0{{ '.' + ntp_area if ntp_area else '' }}.pool.ntp.org iburst"
  - "1{{ '.' + ntp_area if ntp_area else '' }}.pool.ntp.org iburst"
  - "2{{ '.' + ntp_area if ntp_area else '' }}.pool.ntp.org iburst"
  - "3{{ '.' + ntp_area if ntp_area else '' }}.pool.ntp.org iburst"

ntp_restrict:
  - "127.0.0.1"
  - "::1"

package: https://www.openssl.org/source/openssl-1.1.1c.tar.gz
sha256_package: https://www.openssl.org/source/openssl-1.1.1c.tar.gz.sha256

