- name: Configure servers
  hosts: all
  become: yes
  gather_facts: false
  any_errors_fatal: true
  roles:
#    - role: inst_servers
#      server_setup_action: 'user-ssh'
#    - role: inst_servers
#      server_setup_action: 'zabbix-a'
#    - role: inst_servers
#      server_setup_action: 'prepare_host'
    - role: install_ignite
      server_setup_action: 'install'

